# Don't touch pls
ConfigVersion: 7.0

# Login information, this account should only be used by the bot
DiscordEmail: "email@provider.com"
DiscordPassword: "password"

# Listen locations
DiscordServerId: ""
DiscordChatChannelId: ""
DiscordConsoleChannelId: ""

# Game information, this sets the "Playing ______" indicator for the bot, set to "" to disable feature
DiscordGameStatus: "Minecraft"

# Debug options, don't touch unless needed
CancelConsoleCommandIfLoggingFailed: true
DontSendCanceledChatEvents: true
EventDebug: false
ReportCanceledChatEvents: false
RateLimitSleepVerbose: false

# Chat channel information
# The chat channel is the text channel that all messages in-game will be sent to and all messages sent
# to this channel on Discord will be sent in-game
#
# DiscordChatChannelDiscordToMinecraft: whether or not to send messages in the chat channel to the server chat
# DiscordChatChannelMinecraftToDiscord: whether or not to send messages in the server chat to the chat channel
# DiscordChatChannelTruncateLength:     the maximum length of messages from Discord to be sent to Minecraft
#
DiscordChatChannelDiscordToMinecraft: true
DiscordChatChannelMinecraftToDiscord: true
DiscordChatChannelTruncateLength: 100

# Server startup message
# DiscordChatChannelServerStartupMessageEnabled: whether or not to send a message indicating the server is starting up
# DiscordChatChannelServerStartupMessage: message to be sent when server starts
#
DiscordChatChannelServerStartupMessageEnabled: false
DiscordChatChannelServerStartupMessage: "**Server has started**"

# Chat channel player list command
# All the config stuff for the player list command
#
# DiscordChatChannelListCommandEnabled:                    whether the command is enabled
# DiscordChatChannelListCommandMessage:                    the command people can type to get the player list
# DiscordChatChannelListCommandFormatOnlinePlayers:        the message at the beginning of the list (%playercount% will show the current player count)
# DiscordChatChannelListCommandFormatNoOnlinePlayers:      "*No online players*"
#
DiscordChatChannelListCommandEnabled: true
DiscordChatChannelListCommandMessage: "playerlist"
DiscordChatChannelListCommandFormatOnlinePlayers: "Online players (%playercount%):"
DiscordChatChannelListCommandFormatNoOnlinePlayers: "**No online players**"

# Chat channel blacklisted phrases
# DiscordChatChannelBlockedPhrases: Here you can set phrases which if a message is sent in the chat channel containing a phrase here, the message won't be processed
# DiscordChatChannelCutPhrases:     Here you can set phrases which if said in the Minecraft chat will be removed from the message before sending it to the chat channel
#
DiscordChatChannelBlockedPhrases:
- "Online players ("
- "**No online players**"
DiscordChatChannelCutPhrases:
- "@everyone"

# Console channel information
# The console channel is the text channel that receives messages which are then run as server commands
# by the console as well as having the server's logs/latest.log being streamed to line by line
#
# DiscordConsoleChannelEnabled:                  whether or not chat messages in-game are sent to Discord and vice versa as well as executing commands from the console channel
# DiscordConsoleChannelLogRefreshRate:           the amount in milliseconds between checking for new lines of the logs/latest.log file, recommended to not go below 2500 to not hit the rate limit
# DiscordConsoleChannelUsageLog:                 the file that logs all commands being executed by users in the console channel
# DiscordConsoleChannelBlacklistActsAsWhitelist: whether or not the blacklisted commands list acts as a whitelist instead of blacklist
# DiscordConsoleChannelBlacklistedCommands:      phrases wrapped in quotation marks that users should not be able to send as commands to the console
# DiscordConsoleChannelDoNotSendPhrases:         phrases wrapped in quotation marks that should not be sent to the console channel
#
DiscordConsoleChannelEnabled: true
DiscordConsoleChannelLogRefreshRate: 5000
DiscordConsoleChannelUsageLog: "DiscordConsole.log"
DiscordConsoleChannelBlacklistActsAsWhitelist: false
DiscordConsoleChannelBlacklistedCommands:
- "?"
- "op"
- "deop"
DiscordConsoleChannelDoNotSendPhrases:
- "Async Chat Thread"

# Minecraft <-> Discord formatting information
#
# DiscordToMinecraftChatMessageFormat: the format used when sending messages from Discord to Minecraft
# DiscordToMinecraftChatMessageFormatNoRole: the format used when sending messages from Discord to Minecraft when the person doesn't have any roles
# %allroles% = all of the person's roles combined with DiscordToMinecraftAllRolesSeperator between them all
# %message% = message content
# %toprole% = person's highest ranking role
# %toprolecolor% = approximate color of person's highest ranking role
# %username% = person's name on Discord
#
# DiscordToMinecraftAllRolesSeperator: the seperator used in between roles in %allroles%
#
# MinecraftChatToDiscordMessageFormat: the format used when sending messages from Minecraft to Discord
# %displayname% = display name from things like nicknames
# %message% = message content
# %primarygroup% = the name of the user's primary group
# %username% = raw player username
#
DiscordToMinecraftChatMessageFormat: "[&bDiscord &r| %toprolecolor%%toprole%&r] %username%: %message%"
DiscordToMinecraftChatMessageFormatNoRole: "[&bDiscord&r] %username%: %message%"
DiscordToMinecraftAllRolesSeperator: " | "
MinecraftChatToDiscordMessageFormat: "**%primarygroup%** %displayname%: %message%"

# Player join/leave messages
#
# %displayname% = display name from things like nicknames
# %username% = raw player username
#
MinecraftPlayerJoinMessageEnabled: true
MinecraftPlayerJoinMessageFormat: "**%displayname% joined the server**"
MinecraftPlayerLeaveMessageEnabled: true
MinecraftPlayerLeaveMessageFormat: "**%displayname% left the server**"

# Player death messages
# Whether or not to send death messages to the chat channel as well
#
MinecraftPlayerDeathMessageEnabled: true

# Unsubscribed user message forwarding
# Whether or not people who are unsubscribed from Discord chat messages will still have their messages
# sent to the chat channel, yet still not see anything from the chat channel
#
MinecraftUnsubscribedMessageForwarding: false

# Achievement messages
# MinecraftPlayerAchievementMessagesEnabled: whether or not to send achievement messages to the chat channel as well
#
# MinecraftPlayerAchievementMessagesFormat: the format used when sending achievement messages from Minecraft to Discord
# %achievement% = message content
# %displayname% = display name from things like nicknames
# %username% = raw player username
# %world% = the name of the user's primary group
#
MinecraftPlayerAchievementMessagesEnabled: true
MinecraftPlayerAchievementMessagesFormat: "**%displayname% earned achievement %achievement%!**"